[package]
name = "d6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
tui = "0.19"
tui-logger = "0.8"
crossterm = "0.25"
image = "0.24.6"
minifb = "0.23.0"
tobj = "3.2.4"